language: elixir
elixir:
  - 1.7
otp_release:
  - 21.0
branches:
  only:
    - master
install:
  - epmd -daemon
  - mix local.hex --force
  - mix local.rebar --force
script: make travis
env:
  - MIX_ENV=test
before_script: make travis-init
script: make travis
before_deploy: make travis-deploy
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure:
  on:
    repo: ArcBlock/blockchain-rpc
    branch: master
